import type { Metadata } from 'next'
import { Open_Sans  } from 'next/font/google'
import './globals.css'
const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // Regular, SemiBold, Bold
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`overflow-hidden ` + openSans.className}>{children}</body>
    </html>
  )
}
